In [ ]:
import pandas as pd
df= pd.read_csv('/content/nba.csv')
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

** Shape() is use for no of rows and coloums.***

In [ ]:
df.shape # Finding the no of rows and coloumns.

(458, 9)

In [ ]:
df.head(5)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [ ]:
df.tail(5)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd
data=pd.read_csv(r"/content/nba.csv")
data =pd.Series(data.Age) # series
#data =pd.DataFrame(data)   # Datafram
data

0      25.0
1      25.0
2      27.0
3      22.0
4      29.0
       ...
453    26.0
454    24.0
455    26.0
456    26.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
print(r'hll\noo')

hll\noo

+***List**

1. Lists are used to store multiple items in a single variable.
2. Lists are created using square brackets:[]
3. List items are ordered, changeable, and allow duplicate values.

***Series**  1D Column

In [ ]:

newlst  =["a","b","c"]
print(newlst)

['a', 'b', 'c']

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
lst =["pune","nashik","surat","goa"]
print(lst)
newlist =pd.Series(lst)
print(newlist)

['pune', 'nashik', 'surat', 'goa']
0      pune
1    nashik
2     surat
3       goa
dtype: object

In [ ]:
newlist =pd.DataFrame(lst)
print(newlist)

        0
0    pune
1  nashik
2   surat
3     goa

In [ ]:
print(newlist[:2]) # slicing

        0
0    pune
1  nashik

***DataFrame** 2d ,
column and rows

In [ ]:
import pandas as pd

list1 =[1,2,3]
newlist= pd.DataFrame(list1,index=[1,2,3], dtype=float)

print(newlist)

     0
1  1.0
2  2.0
3  3.0

In [ ]:
newlist = list1.index(1)
newlist

0

***Slicing**

In [ ]:
print(newlist[:2])

     0
1  1.0
2  2.0

In [ ]:
lis

In [ ]:
a= ["a","b","c"]
ab =a.index('a')
print(ab)

0

In [ ]:
ls =pd.DataFrame(lst)
print(ls)

   0
0  1
1  2
2  3
3  4

***Tuple***

* Tuples are used to store multiple items in a single variable.
* Tuples are written with round brackets.
* Tuple items are ordered, unchangeable, and allow duplicate values.

In [ ]:
a=("a","b","c")
myval =pd.series(a,index=["a","b"])

('a', 'b', 'c')

In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar["y"])

7

***Tuple**

In [ ]:
studentlst =("a","b","c") #studentlst
print(type(studentlst))

<class 'tuple'>

In [ ]:
dict = {'name':'priya',
'rollno':'suraj'}

print(type(dict))

<class 'dict'>

In [ ]:
dict1 ={'name':['abc','baba'],
        'salary':[5,4]}
print(type(dict1))

<class 'dict'>

In [ ]:
import pandas as pd
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
df= pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [10]:
import pandas as pd
df = pd.read_csv("/content/nba.csv")
print(df)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN

[458 rows x 9 columns]

In [11]:
df.shape

(458, 9)

In [ ]:
df.head()

In [ ]:
import pandas as pd
df =pd.read_csv('/content/nba.csv',index_col="Name")
print(df)
# retrieving row by loc method

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
...                       ...     ...      ...   ...    ...     ...
Shelvin Mack        Utah Jazz     8.0       PG  26.0    6-3   203.0
Raul Neto           Utah Jazz    25.0       PG  24.0    6-1   179.0
Tibor Pleiss        Utah Jazz    21.0        C  26.0    7-3   256.0
Jeff Withey         Utah Jazz    24.0        C  26.0    7-0   231.0
NaN                       NaN     NaN      NaN   NaN    NaN     NaN

                         College     Salary
Name
Avery Bradley              Texas  7730337.0
Jae Crowder            Marquette  6796117.0
John Holland   Boston University        NaN
R.J. Hunter        Georgia State  1148640.0
Jonas Jerebko                NaN  5000000.0
...                          ...        ...
Shelvin Mack              Butler  2433333.0
Raul Neto                    NaN   900000.0
Tibor Pleiss                 NaN  2900000.0
Jeff Withey               Kansas   947276.0
NaN                          NaN        NaN

[458 rows x 8 columns]

***Indexing a DataFrame using .iloc[ ] :
This function allows us to retrieve rows and columns by position. In order to do that, we’ll need to specify the positions of the rows that we want, and the positions of the columns that we want as well. The df.iloc indexer is very similar to df.loc but only uses integer locations to make its selections.***

In [ ]:
first = df.loc["Avery Bradley"]
second = df.loc["Jeff Withey"]


print(first, "\n\n\n", second)

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object


 Team        Utah Jazz
Number           24.0
Position            C
Age              26.0
Height            7-0
Weight          231.0
College        Kansas
Salary       947276.0
Name: Jeff Withey, dtype: object

***Selecting a single columns
In order to select a single column, we simply put the name of the column in-between the brackets***

In [ ]:
first= df['Team']
print(first)

Name
Avery Bradley    Boston Celtics
Jae Crowder      Boston Celtics
John Holland     Boston Celtics
R.J. Hunter      Boston Celtics
Jonas Jerebko    Boston Celtics
                      ...
Shelvin Mack          Utah Jazz
Raul Neto             Utah Jazz
Tibor Pleiss          Utah Jazz
Jeff Withey           Utah Jazz
NaN                         NaN
Name: Team, Length: 458, dtype: object

In [ ]:
# retrieving rows by iloc method
row2 = df.iloc[3]
print(row2)

Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

***loc get rows and coloum uisng lable**

In [ ]:
df.loc[:'R.J. Hunter']

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0

***iloc get rows and coloum  using index number***

In [ ]:
df.iloc[:5]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [ ]:
df= pd.read_csv('/content/nba.csv')
df.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

In [ ]:
ser = pd.Series(df['Name'])
ser.head(5)
print(ser,"\n")

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [ ]:
before = df.dtypes
print("before conversion:", before, "\n")

before conversion: Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [ ]:
data = df.drop_duplicates()
print(df)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN

[458 rows x 9 columns]

In [ ]:
data.dropna(inplace = True)


# converting dtypes using astype
data["Salary"]= data["Salary"].astype(int)
data["Number"]= data["Number"].astype(str)

# storing dtype after converting
after = data.dtypes

# printing to compare
# printing to compare
print("AFTER CONVERSION\n", after, "\n")

AFTER CONVERSION
 Name         object
Team         object
Number       object
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary        int64
dtype: object

In [ ]:
a = 10
print(a)
print(type(a))

10
<class 'int'>

In [ ]:
print("hello")

hello